'''
Created Date: 2023-09-25
Qn: You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more
    letter at a random position.

    Return the letter that was added to t.
Link: https://leetcode.com/problems/find-the-difference/
Notes:
    - can use ascii sum, bit manipulation with xor and hashmap
'''
def findTheDifference(s: str, t: str) -> str:
    s_sum = sum(ord(c) for c in s)
    t_sum = sum(ord(c) for c in t)
    return chr(t_sum - s_sum)

if __name__ == '__main__':
    s1, t1 = "abcd", "abcde"
    s2, t2 = "", "y"
    
    print(findTheDifference(s1, t1))
    print(findTheDifference(s2, t2))
